/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransferenciasRouteImport } from './routes/_authenticated/transferencias'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedConsultasRouteImport } from './routes/_authenticated/consultas'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFamiliasIndexRouteImport } from './routes/_authenticated/familias.index'
import { Route as AuthenticatedFamiliasIdRouteImport } from './routes/_authenticated/familias.$id'

const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransferenciasRoute =
  AuthenticatedTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultasRoute = AuthenticatedConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliasIndexRoute =
  AuthenticatedFamiliasIndexRouteImport.update({
    id: '/familias/',
    path: '/familias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFamiliasIdRoute = AuthenticatedFamiliasIdRouteImport.update({
  id: '/familias/$id',
  path: '/familias/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/familias/': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/transferencias': typeof AuthenticatedTransferenciasRoute
  '/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/familias': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/consultas': typeof AuthenticatedConsultasRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/transferencias': typeof AuthenticatedTransferenciasRoute
  '/_authenticated/familias/$id': typeof AuthenticatedFamiliasIdRoute
  '/_authenticated/familias/': typeof AuthenticatedFamiliasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/agenda'
    | '/avisos'
    | '/consultas'
    | '/mapa'
    | '/painel'
    | '/transferencias'
    | '/familias/$id'
    | '/familias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/admin'
    | '/agenda'
    | '/avisos'
    | '/consultas'
    | '/mapa'
    | '/painel'
    | '/transferencias'
    | '/familias/$id'
    | '/familias'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/avisos'
    | '/_authenticated/consultas'
    | '/_authenticated/mapa'
    | '/_authenticated/painel'
    | '/_authenticated/transferencias'
    | '/_authenticated/familias/$id'
    | '/_authenticated/familias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transferencias': {
      id: '/_authenticated/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof AuthenticatedTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultas': {
      id: '/_authenticated/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AuthenticatedConsultasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias/': {
      id: '/_authenticated/familias/'
      path: '/familias'
      fullPath: '/familias/'
      preLoaderRoute: typeof AuthenticatedFamiliasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familias/$id': {
      id: '/_authenticated/familias/$id'
      path: '/familias/$id'
      fullPath: '/familias/$id'
      preLoaderRoute: typeof AuthenticatedFamiliasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedConsultasRoute: typeof AuthenticatedConsultasRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedTransferenciasRoute: typeof AuthenticatedTransferenciasRoute
  AuthenticatedFamiliasIdRoute: typeof AuthenticatedFamiliasIdRoute
  AuthenticatedFamiliasIndexRoute: typeof AuthenticatedFamiliasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedConsultasRoute: AuthenticatedConsultasRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedTransferenciasRoute: AuthenticatedTransferenciasRoute,
  AuthenticatedFamiliasIdRoute: AuthenticatedFamiliasIdRoute,
  AuthenticatedFamiliasIndexRoute: AuthenticatedFamiliasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
